name: CI

on:
  - push
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          pip install flake8
          export PYTHONPATH=`pwd`:$PYTHONPATH
          flake8
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:

          - python-version: "3.8"
            django-version: Django==3.2

          - python-version: "3.8"
            django-version: Django==4.1

          - python-version: "3.8"
            django-version: Django==4.2

          - python-version: "3.9"
            django-version: Django==3.2

          - python-version: "3.9"
            django-version: Django==4.1

          - python-version: "3.9"
            django-version: Django==4.2

          - python-version: "3.10"
            django-version: Django==3.2

          - python-version: "3.10"
            django-version: Django==4.1

          - python-version: "3.10"
            django-version: Django==4.2

          - python-version: "3.10"
            django-version: Django==5.0rc1

          - python-version: "3.11"
            django-version: Django==3.2

          - python-version: "3.11"
            django-version: Django==4.1

          - python-version: "3.11"
            django-version: Django==4.2

          - python-version: "3.11"
            django-version: Django==5.0rc1

          - python-version: "3.12"
            django-version: Django==4.2

          - python-version: "3.12"
            django-version: Django==5.0rc1

    name: Run Python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
          pip install pytest coverage pytest-cov ${{ matrix.django-version }}
          export PYTHONPATH=`pwd`:$PYTHONPATH
          pytest
